const gitmojis = [
  ":art:",
  ":zap:",
  ":fire:",
  ":bug:",
  ":ambulance:",
  ":sparkles:",
  ":pencil:",
  ":rocket:",
  ":lipstick:",
  ":tada:",
  ":white_check_mark:",
  ":lock:",
  ":apple:",
  ":penguin:",
  ":checkered_flag:",
  ":robot:",
  ":green_apple:",
  ":bookmark:",
  ":rotating_light:",
  ":construction:",
  ":green_heart:",
  ":arrow_down:",
  ":arrow_up:",
  ":pushpin:",
  ":construction_worker:",
  ":chart_with_upwards_trend:",
  ":recycle:",
  ":whale:",
  ":heavy_plus_sign:",
  ":heavy_minus_sign:",
  ":wrench:",
  ":globe_with_meridians:",
  ":pencil2:",
  ":poop:",
  ":rewind:",
  ":twisted_rightwards_arrows:",
  ":package:",
  ":alien:",
  ":truck:",
  ":page_facing_up:",
  ":boom:",
  ":bento:",
  ":ok_hand:",
  ":wheelchair:",
  ":bulb:",
  ":beers:",
  ":speech_balloon:",
  ":card_file_box:",
  ":loud_sound:",
  ":mute:",
  ":busts_in_silhouette:",
  ":children_crossing:",
  ":building_construction:",
  ":iphone:",
  ":clown_face:",
  ":egg:",
  ":see_no_evil:",
  ":camera_flash:",
  ":alembic:",
  ":mag:",
  ":wheel_of_dharma:",
  ":label:",
  ":book:",
  ":heart:",
  ":cn:",
  ":kr:"
];

module.exports = {
  rules: {
    "type-enum": [1, "always", gitmojis],
    "header-max-length": [1, "always", 100],
    "body-leading-blank": [2, "always"],
    "footer-leading-blank": [2, "always"],
    "scope-case": [1, "always", "lower-case"],
    "subject-case": [1, "always", ["sentence-case"]],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", ["."]],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"]
  },
  parserPreset: {
    parserOpts: {
      headerPattern: /^(:\w*:)(?:\s*(.*):)? (.*)$/,
      headerCorrespondence: ["type", "scope", "subject"]
    }
  }
};
