on:
  schedule:
    - cron: "0 8 * * 0"
name: Daily Jobs
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Renovate
        uses: renovatebot/github-action@v1.0.0
        with:
          configurationFile: renovate.config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
