on:
  schedule:
    - cron: "0 8 * * *"
name: Daily Jobs
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Renovate
        uses: vidavidorra/github-action-renovate@v1.0.5
        with:
          configurationFile: renovate.config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
